POST http://localhost:3000/api/Blog/Comment
Content-Type: application/json

{
  "blog_id": "abc123",
  "name": "John Doe",
  "email": "johndoe@example.com",
  "comment": "This is a sample comment on the blog post.",
  "parent_comment_id": null
}



###

GET http://localhost:3000/api/Blog/2/Comments/
Content-Type: application/json